# Generated by Django 4.0.6 on 2022-07-30 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook_app', '0002_book_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ProfileImage',
            field=models.FileField(default='avatar.png', upload_to='profiles/'),
        ),
    ]
